# Run this first to load everything needed
.libPaths("/projects/standard/mrunj/shared/Rlibs_schla103")
library(dplyr)
library(ggplot2)
library(tibble)
library(tidyr)
library(scales)
library(data.table)
library(gridExtra)
library(reshape2) # check if we need this
library(fields)
library(Matrix)
library(MASS) # check if we need this
#library(bigsparser)
#require(rhdf5)
library(parallel)
library(parallelly)
library(ape) # check if we need this
library(sf)
library(raster)
library(stars)
library(marmap)
library(terra)
library(units)
library(sfheaders)
library(ggspatial)

source('functions/main_sim_functions.R')
source('functions/plotting_functions.R')
source('functions/utility_functions.R')
source('functions/neutral_landscape.R')