---
title: "Untitled"
output: html_document
date: "2025-09-19"
---

```{r setup, include=FALSE}
library(tidyverse)
library(scales)
library(gridExtra)
library(reshape2)
library(fields)
library(Matrix)

source('functions/f_RunIBM.R')
source('functions/f_RunMatrixSimFlat.R')
source('functions/plotting_functions.R')
source('functions/utility_functions.R')
```

# Parameters

```{r}
nx <- 10 # size of space in the x dimension
ny <- 10 # size of space in the y dimension

nsteps <- 5000 # timesteps

# dispersal kernel is a gamma distribution, shape=alpha, scale=theta
v_alphas <- seq(from=0.01,to=5,length.out=5) # values the shape parameter can take
v_thetas <- seq(from=0.01,to=5,length.out=5) # values the scale parameter can take
alpha_start <- 3 # index (in v_alphas) of shape parameter initial value
theta_start <- 3 # index in (v_thetas) of scale parameter initial value

# plasticity parameter currently doesn't affect anything or evolve
v_p <- seq(from=0,to=0.9,length.out=2) # values the plasticity parameter can take
p_start <- 1 # index (in v_p) of plasticity parameter initial value

mu <- 0.01 # mutation frequency
# mutation increment specified by v_alphas, v_thetas

# habitat quality (as represented by reproductive output)
n_bad <- 0*round(nx*ny/4)
n_good <- 0*round(nx*ny/4)
b_bad <- 2
b_neutral <- 10
b_good <- 18
b <- matrix(b_neutral, nrow=ny,ncol=nx)
b[sample(nx*ny,n_bad+n_good)] <- c(rep(b_bad,n_bad),rep(b_good,n_good))

# habitat quality (as represented by carrying capacity)
n_good <- .5*nx*ny
K <- matrix(5, nrow=ny,ncol=nx)
#K[sample(nx*ny,n_good)] <- 10
#K[,c(1,2,3,11,12,13)] <- 3
K[1:3,1:3] <- 10
K[8:10,8:10] <- 10

  
# K <- data.frame(site=1:(nx*ny),K_i=5)
# K$K_i[sample(nx*ny,n_bad)] <- 1
```

```{r}
matrix_flat_out <- f_RunMatrixSimFlat(nx,ny,nsteps,v_alphas,v_thetas,v_p,alpha_start=3,theta_start=3,p_start,mu,b,b_bad,b_neutral,b_good,K,plot_kernel_dynamic=TRUE)

f_PlotOutput(matrix_flat_out$by_t, kern_timesteps=seq(from=0.75*nsteps,to=nsteps,length.out=25))
summarize(filter(matrix_flat_out$by_t,t>=0.75*nsteps),med_alpha=median(alpha),med_theta=median(theta))
f_PlotAllHeatmaps(matrix_flat_out$sim_melt,matrix_flat_out$patch_locations,plot_int=c(seq(from=300,to=800,by=100),seq(from=2500,to=3000,by=100)))
```

```{r}
alpha_start <- 3
theta_start <- 3
matrix_flat_out_2 <- f_RunMatrixSimFlat(nx,ny,nsteps,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,b_bad,b_neutral,b_good,K,competition_method = 'sample')

f_PlotOutput(matrix_flat_out_2$by_t, kern_timesteps=seq(from=0.75*nsteps,to=nsteps,length.out=25))
summarize(filter(matrix_flat_out_2$by_t,t>=0.75*nsteps),med_alpha=median(alpha),med_theta=median(theta))
f_PlotAllHeatmaps(matrix_flat_out_2$sim_melt,matrix_flat_out$patch_locations)
```

## old stuff

```{r}
#Rprof(filename='prof_matrixsample.out')
matrix_out <- f_RunMatrixSim(nx,ny,nsteps,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,b_bad,b_neutral,b_good,K,heatmap_plot_int = 500, competition_method = 'sample')
#Rprof(NULL)

matrix_out[[4]]

#summaryRprof('prof_matrixsample.out')

f_PlotOutput(matrix_out[[2]], kern_timesteps=seq(from=0.75*nsteps,to=nsteps,length.out=25))
f_PlotAllHeatmaps(matrix_out[[1]],matrix_out[[3]])
#save(K, IBM_out,file='model_runs/20251017_1.RData')
```

```{r}
#load('model_runs/20251017_1.RData')
#Rprof(filename='prof_IBM.out')
IBM_out <- f_RunIBM(nx,ny,nsteps,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,b_bad,b_neutral,b_good,K,heatmap_plot_int = 500)
#Rprof(NULL)
#summaryRprof('prof_IBM.out')

IBM_out[[4]]

f_PlotOutput(IBM_out[[2]], kern_timesteps=seq(from=0.75*nsteps,to=nsteps,length.out=25))
f_PlotAllHeatmapsIBM(IBM_out[[1]],IBM_out[[3]])
#save(b, IBM_out,file='model_runs/20251022_3.RData')
```



# Multiple runs at a time
## Matrix
```{r}
nx <- 10 # size of space in the x dimension
ny <- 10 # size of space in the y dimension

nsteps <- 3000 # timesteps

# dispersal kernel is a gamma distribution, shape=alpha, scale=theta
# v_alphas <- seq(from=0.01,to=5,length.out=5) # values the shape parameter can take
# v_thetas <- seq(from=0.01,to=5,length.out=5) # values the scale parameter can take
v_alphas <- seq(from=1.5,to=2.5,length.out=5) # values the shape parameter can take
v_thetas <- seq(from=0.25,to=1.25,length.out=5) # values the scale parameter can take

# plasticity parameter currently doesn't affect anything or evolve
v_p <- seq(from=0,to=0.9,length.out=2) # values the plasticity parameter can take
p_start <- 1 # index (in v_p) of plasticity parameter initial value

mu <- 0.01 # mutation frequency
# mutation increment specified by v_alphas, v_thetas

# habitat quality (as represented by reproductive output)
n_bad <- 0*round(nx*ny/4)
n_good <- 0*round(nx*ny/4)
b_bad <- 2
b_neutral <- 5
b_good <- 18
b <- matrix(b_neutral, nrow=ny,ncol=nx)
# b[1:3,1:3] <- b_good
# b[8:10,8:10] <- b_good
#b[sample(nx*ny,n_bad+n_good)] <- c(rep(b_bad,n_bad),rep(b_good,n_good))

# habitat quality (as represented by carrying capacity)
K <- matrix(10, nrow=ny,ncol=nx)
# K[1:3,1:3] <- 20
# K[8:10,8:10] <- 20

sims <- data.frame()
# original param set
sims <- expand.grid(alpha_start=1:length(v_alphas),theta_start=1:length(v_thetas)) %>%
  mutate(sim_num=row_number())

df_out <- data.frame(t=NA,alpha=NA,theta=NA,popsize=NA,sim_num=NA)
for(i in 1:nrow(sims)){
  print(i)
  matrix_out <- f_RunMatrixSimFlat(nx,ny,nsteps,v_alphas,v_thetas,v_p,
                                   sims$alpha_start[i],sims$theta_start[i],p_start,mu,b,b_bad,b_neutral,b_good,K)$by_t %>%
    mutate(sim_num=sims$sim_num[i])
  df_out <- rbind(df_out,matrix_out)
}

df_out <- filter(df_out,!is.na(sim_num),popsize>0) %>%
  arrange(t) %>%
  mutate(sim_num=as.factor(sim_num))
lasts <- group_by(df_out,sim_num)%>%
  summarize(alpha=last(alpha),theta=last(theta),t=last(t))
ggplot(df_out,aes(x=alpha,y=theta,color=sim_num))+
    geom_path(lwd=0.25)+
  geom_point(data=lasts,aes(x=alpha,y=theta,color=sim_num,fill=(t==nsteps)),pch=21,size=3)+
  scale_fill_manual(name='population persistence', values=c('black','white'))+ # ones filled in black died out before the end of the simulation
    theme_minimal()
#save(df_out,sims,file='model_runs/20251031_4.RData')
#f_PlotOutput(filter(df_out,sim_num==2),kern_timesteps=seq(from=0.75*nsteps,to=nsteps,length.out=25),kern_xlim=5)
```
## IBM
```{r}
incrs <- 20 # specify number of increments in v_alpha and v_theta
nx <- 5 # size of space in the x dimension
ny <- 5 # size of space in the y dimension

nsteps <- 50 # timesteps

# plasticity parameter currently doesn't affect anything or evolve
v_p <- seq(from=0,to=0.9,length.out=2) # values the plasticity parameter can take
p_start <- 1 # index (in v_p) of plasticity parameter initial value
mu <- 0.01 # mutation frequency
# mutation increment specified by v_alphas, v_thetas
b=3
K=60

sims <- data.frame()
# original param set
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))
# different starting spots
sims <- rbind(sims,data.frame(alpha_start=incrs,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=incrs,theta_from=0.1, theta_to=5,theta_nout=incrs))
sims <- rbind(sims,data.frame(alpha_start=incrs,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=incrs,theta_from=0.1, theta_to=5,theta_nout=incrs))
# keep theta constant
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=0.1,theta_nout=2))
# keep alpha constant
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=0.1,alpha_nout=2,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))
colnames(sims)=c('alpha_start','alpha_from','alpha_to','alpha_nout','theta_start','theta_from','theta_to','theta_nout')
sims$sim_num <- 1:nrow(sims)


df_out <- data.frame(t=NA,alpha=NA,theta=NA,popsize=NA,sim_num=NA)
for(i in 1:nrow(sims)){
  v_alphas <- seq(from=sims$alpha_from[i],to=sims$alpha_to[i],length.out=sims$alpha_nout[i])
  v_thetas <- seq(from=sims$theta_from[i],to=sims$theta_to[i],length.out=sims$theta_nout[i])
  
  matrix_out <- f_RunIBM(nx,ny,nsteps,v_alphas,v_thetas,v_p,sims$alpha_start[i],sims$theta_start[i],p_start,mu,b)[[2]] %>%
    mutate(sim_num=sims$sim_num[i])
  
  df_out <- rbind(df_out,matrix_out)
}

df_out <- filter(df_out,!is.na(sim_num)) %>%
  arrange(t) %>%
  mutate(sim_num=as.factor(sim_num)) %>%
  mutate(MEAN=alpha*theta,VAR=alpha*(theta^2))

df_out <- filter(df_out,sim_num!=5)

firsts <- group_by(df_out,sim_num)%>%
  summarize(alpha=first(alpha),theta=first(theta),MEAN=first(MEAN),VAR=first(VAR))

lasts <- group_by(df_out,sim_num)%>%
  summarize(alpha=last(alpha),theta=last(theta),MEAN=last(MEAN),VAR=last(VAR))

ggplot(df_out,aes(x=alpha,y=theta,color=sim_num))+
    geom_path(alpha=0.75,lwd=0.25)+
  geom_point(data=lasts,aes(x=alpha,y=theta,fill=sim_num),color='black',pch=21, size=3)+
  geom_point(data=firsts,aes(x=alpha,y=theta,color=sim_num),fill='white',pch=21, size=3)+
      theme_minimal()

sims_last <- first(sims)
v_a <- seq(from=sims_last$alpha_from,to=sims_last$alpha_to,length.out=sims_last$alpha_nout)
v_t <- seq(from=sims_last$theta_from,to=sims_last$theta_to,length.out=sims_last$theta_nout)

all_kerns <- expand.grid(v_a,v_t) %>%
  rename(alpha=Var1,theta=Var2) %>%
  mutate(MEAN=alpha*theta,VAR=alpha*theta^2)

ggplot(df_out,aes(x=MEAN,y=VAR,color=sim_num))+
  geom_point(data=all_kerns,aes(x=MEAN,y=VAR),color='gray',alpha=0.2)+
  geom_path(data=df_out,alpha=0.75,lwd=0.25)+
  geom_point(data=lasts,aes(x=MEAN,y=VAR,fill=sim_num),color='black',pch=21, size=3)+
    theme_minimal()

#save(sims,df_out,file='model_runs/v20_xy5_t50000_init_all.RData')
```

## IBM, but just run the same initial params a bunch of times
```{r}
#load('model_runs/20251023_7.RData')
incrs <- 5 # specify number of increments in v_alpha and v_theta
nx <- 10 # size of space in the x dimension
ny <- 10 # size of space in the y dimension

nsteps <- 5000 # timesteps

# plasticity parameter (currently everyone's set to be plastic, no evolution in p)
v_p <- seq(from=0,to=0.9,length.out=2) # values the plasticity parameter can take
p_start <- 1 # index (in v_p) of plasticity parameter initial value

mu <- 0.01 # mutation frequency
# mutation increment specified by v_alphas, v_thetas

# habitat quality (as represented by reproductive output)
n_bad <- 0
n_good <- 0
b_bad <- 3
b_neutral <- 3
b_good <- 3
b <- matrix(b_neutral, nrow=ny,ncol=nx)
b[sample(nx*ny,n_bad+n_good)] <- c(rep(b_bad,n_bad),rep(b_good,n_good))

# habitat quality (as represented by carrying capacity)
#n_good <- 3
K <- matrix(10, nrow=ny,ncol=nx)

sims <- data.frame()
# original param set
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))
sims <- rbind(sims,data.frame(alpha_start=1,alpha_from=0.1,alpha_to=5,alpha_nout=incrs,theta_start=1,theta_from=0.1, theta_to=5,theta_nout=incrs))

colnames(sims)=c('alpha_start','alpha_from','alpha_to','alpha_nout','theta_start','theta_from','theta_to','theta_nout')
sims$sim_num <- 1:nrow(sims)


df_out <- data.frame(t=NA,alpha=NA,theta=NA,popsize=NA,sim_num=NA)
sim_list <- vector("list",length=nrow(sims))
for(i in 1:nrow(sims)){
  v_alphas <- seq(from=sims$alpha_from[i],to=sims$alpha_to[i],length.out=sims$alpha_nout[i])
  v_thetas <- seq(from=sims$theta_from[i],to=sims$theta_to[i],length.out=sims$theta_nout[i])
  
  IBM_out <- f_RunMatrixSim(nx,ny,nsteps,v_alphas,v_thetas,v_p,sims$alpha_start[i],sims$theta_start[i],p_start,mu,b,b_bad,b_neutral,b_good,K,heatmap_plot_int=500,competition_method = 'sample')
  df_out_i <- IBM_out[[2]] %>%
    mutate(sim_num=sims$sim_num[i])
  
  df_out <- rbind(df_out,df_out_i)
  sim_list[[i]] <- IBM_out
}

df_out <- filter(df_out,!is.na(sim_num)) %>%
  arrange(t) %>%
  mutate(sim_num=as.factor(sim_num)) %>%
  mutate(MEAN=alpha*theta,VAR=alpha*(theta^2))

lasts <- group_by(df_out,sim_num)%>%
  summarize(alpha=last(alpha),theta=last(theta),MEAN=last(MEAN),VAR=last(VAR))

firsts <- group_by(df_out,sim_num)%>%
  summarize(alpha=first(alpha),theta=first(theta))

### plot in alpha-theta space
ggplot(df_out,aes(x=alpha,y=theta,color=sim_num))+
    geom_path(alpha=0.75,lwd=0.25)+
  geom_point(data=lasts,aes(x=alpha,y=theta,fill=sim_num),color='black',pch=21, size=3)+
    theme_minimal()

sims <- last(sims)
v_a <- seq(from=sims$alpha_from,to=sims$alpha_to,length.out=sims$alpha_nout)
v_t <- seq(from=sims$theta_from,to=sims$theta_to,length.out=sims$theta_nout)

all_kerns <- expand.grid(v_a,v_t) %>%
  rename(alpha=Var1,theta=Var2) %>%
  mutate(MEAN=alpha*theta,VAR=alpha*theta^2)

### plot in mean-var space
ggplot(df_out,aes(x=MEAN,y=VAR,color=sim_num))+
  #geom_point(data=all_kerns,aes(x=MEAN,y=VAR),color='gray',alpha=0.2)+
  geom_path(data=df_out,alpha=0.75,lwd=0.25)+
  geom_point(data=lasts,aes(x=MEAN,y=VAR,fill=sim_num),color='black',pch=21, size=3)+
    theme_minimal()


### plot a sampling of kernels
late_kerns <- filter(df_out,t>0.5*max(t))
sample_kerns <- late_kerns[sample(x=nrow(late_kerns),size=100,replace=FALSE),]

ggplot()+
  xlim(0,25)+
  geom_function(fun=dgamma,args=list(shape=median(firsts$alpha),scale=median(firsts$theta)),color='black',lwd=0.75,aes(lty='first'))+
  lapply(1:nrow(sample_kerns), function(i){geom_function(fun=dgamma,args=list(shape=sample_kerns$alpha[i],scale=sample_kerns$theta[i]),alpha=0.3,aes(color=sample_kerns$sim_num[i],lty='last'))})+
  geom_function(fun=dgamma,args=list(shape=median(late_kerns$alpha),scale=median(late_kerns$theta)),color='black',lwd=0.75,aes(lty='last'))+
  scale_linetype_manual(values=c('first' = 'dashed',
                                 'last' = 'solid'),name='Kernel')+
  theme_minimal()+
  theme(legend.position='top')

median(late_kerns$MEAN)
median(late_kerns$VAR)

save(sims,df_out,sim_list,file='model_runs/20251023_9.RData')
```

# One run at a time
## Matrix sim

```{r}
b <- 4
K <- 3

nx=7
ny=7

v_alphas <- seq(from=0.01,to=5,length.out=5) # values the shape parameter can take
v_thetas <- seq(from=0.01,to=5,length.out=5) # values the scale parameter can take
alpha_start=2
theta_start=2

# plasticity parameter currently doesn't affect anything or evolve
v_p <- seq(from=0,to=0.9,length.out=2) # values the plasticity parameter can take
p_start <- 1 # index (in v_p) of plasticity parameter initial value

mu <- 0.01 # mutation frequency
# mutation increment specified by v_alphas, v_thetas
```

```{r}

source('f_RunMatrixSim_stoch.r')
stoch_out <- f_RunMatrixSim_stoch(nx=7,ny=7,nsteps=20,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,K=1)
f_PlotOutput(stoch_out[[2]],kern_timesteps=seq(from=1500,by=50,to=2000),kern_xlim=25)
```


```{r}
matrix_out_sample <- f_RunMatrixSim(nx=2,ny=20,nsteps=2000,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,K=3,
                                    heatmap_plot_int=5000,competition_method = 'sample')

matrix_out_sample[[4]]
f_PlotAllHeatmaps(matrix_out_sample[[1]],matrix_out_sample[[3]])
#f_PlotBubbleMatrix(matrix_out_sample[[1]],matrix_out_sample[[3]])
f_PlotOutput(matrix_out_sample[[2]],kern_timesteps=seq(from=1500,by=50,to=2000),kern_xlim=25)
summarize(matrix_out_sample[[2]][1000:2000,],med_alpha=median(alpha),med_theta=median(theta),med_popsize=median(popsize))

load('model_runs/20251015_2.RData')
#save(matrix_out_sample,file='model_runs/20251015_2.RData')
```

```{r}
matrix_out_rnorm <- f_RunMatrixSim(nx=20,ny=20,nsteps=10,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,K=1,
                                   heatmap_plot_int=5000,competition_method = 'rnorm')

matrix_out_rnorm[[4]]
f_PlotAllHeatmaps(matrix_out_rnorm[[1]],matrix_out_rnorm[[3]])
#f_PlotBubbleMatrix(matrix_out_rnorm[[1]],matrix_out_rnorm[[3]])
f_PlotOutput(matrix_out_rnorm[[2]],kern_timesteps=seq(from=1500,by=50,to=2000),kern_xlim=25)
summarize(matrix_out_rnorm[[2]][1000:2000,],med_alpha=median(alpha),med_theta=median(theta),med_popsize=median(popsize))
```
## Run IBM once

```{r}
IBM_out <- f_RunIBM(nx,ny,nsteps,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,b_bad,b_neutral,b_good,K,heatmap_plot_int = 500)
IBM_out[[4]]

IBM_out_fast <- f_RunIBM_faster(nx,ny,nsteps,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b,b_bad,b_neutral,b_good,K,heatmap_plot_int = 500)



f_PlotAllHeatmapsIBM(IBM_out_fast[[1]],IBM_out_fast[[3]])
f_PlotOutput(IBM_out_fast[[2]], kern_timesteps=seq(from=75,by=5,to=100),kern_xlim = 25)
summarize(IBM_out[[2]][500:1000,],med_alpha=median(alpha),med_theta=median(theta),med_popsize=median(popsize))
# save(IBM_out,file='20251015_1.RData')
# load(file='model_runs/20251015_1.RData')
```

```{r}
b <- 2
IBM_out_2 <- f_RunIBM(nx,ny,nsteps=2000,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu=0.1,b)

f_PlotOutput(IBM_out_2[[2]], kern_timesteps=seq(from=1000,by=20,to=2000))
```

# Run IBM multiple times, look at kernel uncertainty
```{r}
b <- 2

kerns <- data.frame(alpha=NA,theta=NA)
sims <- list()

for(rep_i in 1:10){
  IBM_out <- f_RunIBM(nx,ny,nsteps,v_alphas,v_thetas,v_p,alpha_start,theta_start,p_start,mu,b)
  sims[[rep_i]] <- IBM_out
  
  kerns[rep_i,] <- data.frame(alpha=median(IBM_out$alpha[round(0.6*nsteps):nsteps]),theta=median(IBM_out$theta[round(0.6*nsteps):nsteps]))
}

ggplot()+
  xlim(0,25)+
  geom_function(fun=dgamma, args=list(shape=v_alphas[alpha_start],scale=v_thetas[theta_start]),aes(lty='first'))+
  lapply(1:nrow(kerns), function(i){geom_function(fun=dgamma,args=list(shape=kerns$alpha[i],scale=kerns$theta[i]),color='darkgray',aes(lty='last'))})+
  geom_function(fun=dgamma,args=list(shape=median(kerns$alpha),scale=median(kerns$theta)),color='black',lwd=0.75,aes(lty='last'))+
  scale_linetype_manual(values=c('first' = 'dashed',
                                 'last' = 'solid'),name='Kernel')+
  theme_minimal()+
  theme(legend.position='top')
```


